### ISSUE TITLE
Package does not exist

### ISSUE THREAD

**Issue by weiyentan** [cloudbase/cloudbase-init-offline-install#9]
I get an error to say package does not exist...but its not apparent what i should write there.

C:\Git\cloudbase-init-offline-install\NewNanoServerImage.ps1 : A parameter cannot be found that matches parameter name 'Packages'.
At line:1 char:1
+ .\NewNanoServerImage.ps1 -IsoPath $isoPath -TargetPath $targetPath -A ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [NewNanoServerImage.ps1], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,NewNanoServerImage.ps1

**Comment by ader1990** [comment]
fixed by this PR: https://github.com/cloudbase/cloudbase-init-offline-install/pull/7
